import asyncio
import asyncpg
import os
from dotenv import load_dotenv

load_dotenv()

async def install_tables():
    """Install PGQueuer tables directly"""
    DATABASE_URL = os.getenv('DATABASE_URL')
    if not DATABASE_URL:
        print("❌ DATABASE_URL not set")
        return False
    
    print(f"📋 Connecting to database...")
    
    try:
        conn = await asyncpg.connect(DATABASE_URL)
        print("✅ Connected to database")
        
        # Create pgqueuer_status enum type
        await conn.execute("""
            DO $$ BEGIN
                CREATE TYPE pgqueuer_status AS ENUM ('queued', 'picked', 'successful', 'exception', 'canceled', 'deleted');
            EXCEPTION
                WHEN duplicate_object THEN null;
            END $$;
        """)
        print("✅ Created pgqueuer_status enum")
        
        # Create pgqueuer table
        await conn.execute("""
            CREATE TABLE IF NOT EXISTS pgqueuer (
                id SERIAL PRIMARY KEY,
                priority INT NOT NULL,
                queue_manager_id UUID,
                created TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
                updated TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
                heartbeat TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
                execute_after TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
                status pgqueuer_status NOT NULL,
                entrypoint TEXT NOT NULL,
                dedupe_key TEXT,
                payload BYTEA,
                headers JSONB
            )
        """)
        print("✅ Created pgqueuer table")
        
        # Create indexes
        await conn.execute("""
            CREATE INDEX IF NOT EXISTS pgqueuer_priority_id_id1_idx 
            ON pgqueuer (priority ASC, id DESC) INCLUDE (id) WHERE status = 'queued'
        """)
        
        await conn.execute("""
            CREATE INDEX IF NOT EXISTS pgqueuer_updated_id_id1_idx 
            ON pgqueuer (updated ASC, id DESC) INCLUDE (id) WHERE status = 'picked'
        """)
        
        await conn.execute("""
            CREATE INDEX IF NOT EXISTS pgqueuer_queue_manager_id_idx 
            ON pgqueuer (queue_manager_id) WHERE queue_manager_id IS NOT NULL
        """)
        
        await conn.execute("""
            CREATE UNIQUE INDEX IF NOT EXISTS pgqueuer_unique_dedupe_key 
            ON pgqueuer (dedupe_key) WHERE ((status IN ('queued', 'picked') AND dedupe_key IS NOT NULL))
        """)
        print("✅ Created indexes")
        
        # Create pgqueuer_log table
        await conn.execute("""
            CREATE TABLE IF NOT EXISTS pgqueuer_log (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                created TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
                job_id BIGINT NOT NULL,
                status pgqueuer_status NOT NULL,
                priority INT NOT NULL,
                entrypoint TEXT NOT NULL,
                traceback JSONB DEFAULT NULL,
                aggregated BOOLEAN DEFAULT FALSE
            )
        """)
        print("✅ Created pgqueuer_log table")
        
        # Create pgqueuer_statistics table
        await conn.execute("""
            CREATE TABLE IF NOT EXISTS pgqueuer_statistics (
                id SERIAL PRIMARY KEY,
                created TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT DATE_TRUNC('sec', NOW() at time zone 'UTC'),
                count BIGINT NOT NULL,
                priority INT NOT NULL,
                status pgqueuer_status NOT NULL,
                entrypoint TEXT NOT NULL
            )
        """)
        
        await conn.execute("""
            CREATE UNIQUE INDEX IF NOT EXISTS pgqueuer_statistics_unique_count 
            ON pgqueuer_statistics (priority, DATE_TRUNC('sec', created at time zone 'UTC'), status, entrypoint)
        """)
        print("✅ Created pgqueuer_statistics table")
        
        # Create pgqueuer_schedules table
        await conn.execute("""
            CREATE TABLE IF NOT EXISTS pgqueuer_schedules (
                id SERIAL PRIMARY KEY,
                expression TEXT NOT NULL,
                entrypoint TEXT NOT NULL,
                heartbeat TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
                created TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
                updated TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
                next_run TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
                last_run TIMESTAMP WITH TIME ZONE,
                status pgqueuer_status DEFAULT 'queued',
                UNIQUE (expression, entrypoint)
            )
        """)
        print("✅ Created pgqueuer_schedules table")
        
        # Create trigger function
        await conn.execute("""
            CREATE OR REPLACE FUNCTION fn_pgqueuer_changed() RETURNS TRIGGER AS $$
            DECLARE
                to_emit BOOLEAN := false;
            BEGIN
                IF TG_OP = 'UPDATE' AND OLD IS DISTINCT FROM NEW THEN
                    to_emit := true;
                ELSIF TG_OP = 'DELETE' THEN
                    to_emit := true;
                ELSIF TG_OP = 'INSERT' THEN
                    to_emit := true;
                ELSIF TG_OP = 'TRUNCATE' THEN
                    to_emit := true;
                END IF;

                IF to_emit THEN
                    PERFORM pg_notify(
                        'ch_pgqueuer',
                        json_build_object(
                            'channel', 'ch_pgqueuer',
                            'operation', lower(TG_OP),
                            'sent_at', NOW(),
                            'table', TG_TABLE_NAME,
                            'type', 'table_changed_event'
                        )::text
                    );
                END IF;

                IF TG_OP IN ('INSERT', 'UPDATE') THEN
                    RETURN NEW;
                ELSIF TG_OP = 'DELETE' THEN
                    RETURN OLD;
                ELSE
                    RETURN NULL;
                END IF;
            END;
            $$ LANGUAGE plpgsql;
        """)
        
        # Create trigger
        await conn.execute("""
            DROP TRIGGER IF EXISTS tg_pgqueuer_changed ON pgqueuer;
            CREATE TRIGGER tg_pgqueuer_changed
            AFTER INSERT OR UPDATE OR DELETE OR TRUNCATE ON pgqueuer
            EXECUTE FUNCTION fn_pgqueuer_changed();
        """)
        print("✅ Created trigger")
        
        await conn.close()
        print("🎉 PGQueuer tables installed successfully!")
        return True
        
    except Exception as e:
        print(f"❌ Failed to install tables: {e}")
        return False

if __name__ == "__main__":
    asyncio.run(install_tables())
